name: Build Sistema C

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'sistema-c/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'sistema-c/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Sistema C (Sistema de Segurança)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-pio-sistema-c-${{ hashFiles('sistema-c/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-sistema-c-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Build Sistema C
      working-directory: ./sistema-c
      run: pio run -e esp32dev

    - name: Check build output
      working-directory: ./sistema-c
      run: |
        ls -la .pio/build/esp32dev/
        echo "Build completed successfully for Sistema C"

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: sistema-c-firmware-${{ github.sha }}
        path: |
          sistema-c/.pio/build/esp32dev/firmware.bin
          sistema-c/.pio/build/esp32dev/firmware.elf
        retention-days: 30
